--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten
with text_io;
use text_io;
package body expressions_RI is
   procedure assert (res : in out asn1SccBoolean; msg : in out asn1SccCharString) is 
   begin
       if not res then
           Put_Line("FAIL: " &  msg);
       else
           Put_Line("PASS: " & msg);
       end if;
   end;

end expressions_RI;
