--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body myfunction_RI is
   procedure result_data (titi : in out asn1SccT_Int32) is 
       procedure Result_Data (Titi : in out asn1SccT_Int32)
           with Import, Convention => C, Link_Name => "myfunction_RI_result_data";
   begin
       Result_Data (Titi);
   end  Result_Data;

   procedure SET_myTimer (Val : in out asn1SccT_UInt32) is
       procedure SET_myTimer (Val : in out asn1SccT_UInt32)
           with Import, Convention => C, Link_Name => "myfunction_RI_SET_myTimer";
    begin
        Set_myTimer (Val);
    end Set_myTimer;

   procedure RESET_myTimer is
       procedure RESET_myTimer
           with Import, Convention => C, Link_Name => "myfunction_RI_RESET_myTimer";
   begin
       RESET_myTimer;
   end RESET_myTimer;
end myfunction_RI;
