#!/usr/bin/env python3
"""Patch the RI stub of the generated, user-editable og_ri.rs for test-instance.

The instance wrapper (og.rs) implements the process type's RI trait
(Og_typeRi) by forwarding `rezult` to og_ri::rezult — the Rust analog of
Ada's og_RI package. Implement it here so that it prints like the C/Ada RI
stubs of this test (test_ada.c / test_c.c), matching the `expected` file.

Idempotent: running it on an already-patched file is a no-op.
"""
import re
import sys

RI_BODY = 'println!("[C] got something]");'

with open(sys.argv[1], 'r') as f:
    content = f.read()

if RI_BODY not in content:
    # Patch the rezult stub generated by RustGenerator (TODO body)
    pattern = (r'pub unsafe fn rezult\((?P<params>[^)]*)\) \{\n'
               r'    // TODO: implement this RI\n'
               r'\}')
    new_content, count = re.subn(
        pattern,
        lambda m: (f'pub unsafe fn rezult({m.group("params")}) {{\n'
                   f'    {RI_BODY}\n}}'),
        content)
    if count != 1:
        sys.exit(f'patch_ri.py: expected exactly one "rezult" RI stub with '
                 f'a TODO body in {sys.argv[1]}, found {count}')
    content = new_content

with open(sys.argv[1], 'w') as f:
    f.write(content)
