TASTE-Dataview DEFINITIONS ::=
BEGIN

EmptySeq ::= SEQUENCE {}

NullType ::= NULL

ChoiceWithEmptySeq ::= CHOICE {
  a NULL,
  b EmptySeq,
  c NullType
}

c1 EmptySeq ::= {}

n1 NullType ::= NULL

c2 ChoiceWithEmptySeq ::= a: NULL
c3 ChoiceWithEmptySeq ::= b: {}
c4 ChoiceWithEmptySeq ::= c: NULL



END
