--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten
with Text_IO; use Text_IO;

package body orchestrator_RI is
   procedure VESAT_one_step (vesat_input : in out asn1SccT_GNC_LV_SIM_INPUTS)
   is
--       procedure VESAT_one_step (vesat_input : in out asn1SccT_GNC_LV_SIM_INPUTS)
--           with Import;
   begin
       Put_Line ("VESAT One Step called");
   end VESAT_One_Step;

   procedure plot (gnc_data : in out asn1SccT_Plot) is null;
   procedure jump_to_next_major_cycle is null;
   procedure gnc_onestep (gnc_inputs : in out asn1SccT_GNC_LV_SIM_CONTEXT; gnc_outputs : out asn1SccT_GNC_LV_SIM_INPUTS) is null;
   procedure gnc_init is null;
end orchestrator_RI;
