/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "dataview.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeqDef_d_Initialize(asn1SccSeqDef_d* pVal)
{
    *pVal = (asn1SccSeqDef_d) {
    .thanassis = FALSE
};
}
#endif

 
flag asn1SccSeqDef_d_IsConstraintValid(const asn1SccSeqDef_d* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeqDef_c_Initialize(asn1SccSeqDef_c* pVal)
{
    *pVal = (asn1SccSeqDef_c) 8;
}
#endif

 
flag asn1SccSeqDef_c_IsConstraintValid(const asn1SccSeqDef_c* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (8 <= *pVal && *pVal <= 255);
	*pErrCode = ret ? 0 : ERR_asn1SccSeqDef_c;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeqDef_b_Initialize(asn1SccSeqDef_b* pVal)
{
    *pVal = (asn1SccSeqDef_b) 10;
}
#endif

 
flag asn1SccSeqDef_b_IsConstraintValid(const asn1SccSeqDef_b* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (10 <= *pVal && *pVal <= 20);
	*pErrCode = ret ? 0 : ERR_asn1SccSeqDef_b;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeqDef_Initialize(asn1SccSeqDef* pVal)
{
    *pVal = (asn1SccSeqDef) {
    .a = TRUE,
    .b = 15,
    .c = 8,
    .d = {
        .thanassis = TRUE
    },
    .exist = {
        .a = 1,
        .b = 1,
        .d = 1
    }
};
}
#endif

 
flag asn1SccSeqDef_IsConstraintValid(const asn1SccSeqDef* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	if (pVal->exist.a==1) {
	    ret = TRUE; *pErrCode = 0;
	}
	if (ret) {
	    if (pVal->exist.b==1) {
	        ret = asn1SccSeqDef_b_IsConstraintValid(&pVal->b, pErrCode);
	    }
	    if (ret) {
	        ret = asn1SccSeqDef_c_IsConstraintValid(&pVal->c, pErrCode);
	        if (ret) {
	            if (pVal->exist.d==1) {
	                ret = asn1SccSeqDef_d_IsConstraintValid(&pVal->d, pErrCode);
	            }
	        
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeq_b_Initialize(asn1SccSeq_b* pVal)
{
    *pVal = (asn1SccSeq_b) {
    .b_C = FALSE,
    .exist = {
        .b_C = 1
    }
};
}
#endif

 
flag asn1SccSeq_b_IsConstraintValid(const asn1SccSeq_b* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	if (pVal->exist.b_C==1) {
	    ret = TRUE; *pErrCode = 0;
	}


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSeq_Initialize(asn1SccSeq* pVal)
{
    *pVal = (asn1SccSeq) {
    .a = FALSE,
    .b = {
        .b_C = FALSE,
        .exist = {
            .b_C = 1
        }
    },
    .exist = {
        .a = 1,
        .b = 1
    }
};
}
#endif

 
flag asn1SccSeq_IsConstraintValid(const asn1SccSeq* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	if (pVal->exist.a==1) {
	    ret = TRUE; *pErrCode = 0;
	}
	if (ret) {
	    if (pVal->exist.b==1) {
	        ret = asn1SccSeq_b_IsConstraintValid(&pVal->b, pErrCode);
	    }
	
	}

	return ret;
}

