-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
WITH TASTE_BasicTypes;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;


PACKAGE BODY TASTE_Dataview IS



FUNCTION asn1SccLight_Init return asn1SccLight
IS 
BEGIN
    RETURN asn1Sccred;
END asn1SccLight_Init;

FUNCTION asn1SccLight_Equal(val1, val2: in asn1SccLight) return Boolean
IS 
BEGIN
    RETURN val1 = val2;
END asn1SccLight_Equal;

 

END TASTE_Dataview;