TASTE-Dataview DEFINITIONS ::=
BEGIN

    MyInt ::= INTEGER (0..255)
    MyChoice ::= CHOICE {
        a BOOLEAN,
        b MyInt
    }
   MyDets ::= ENUMERATED { a, b }  -- match the CHOICE options

END
