--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten
with text_io; use text_io;
package body og_RI is
   procedure rezult(ze_rezult : in out asn1SccMy_OctStr) is
   begin
       Put_Line ("[C] got something");
   end rezult;
end og_RI;
