--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body challenge_RI is
   procedure pow (a : in out asn1SccT_UInt32; b : in out asn1SccT_UInt32; res : out asn1SccT_UInt32) is 
       procedure pow (a : in out asn1SccT_UInt32; b : in out asn1SccT_UInt32; res : out asn1SccT_UInt32) with Import, Convention => C, Link_Name => "challenge_RI_pow";
   begin
       Pow (a, b, res);
   end Pow;

end challenge_RI;
