all:
	mkdir -p code
	cd code && opengeode --toAda /home/taste/opengeode/tests/testsuite/test-via/challenge.pr 
	asn1scc -fp AUTO -typePrefix asn1Scc -o code -equal -Ada dataview-uniq.asn code/challenge_datamodel.asn
	cd code && gnat make challenge
clean:
	rm -rf code