TASTE-Dataview DEFINITIONS ::=
BEGIN

Int32 ::= INTEGER (-2147483648 .. 2147483647)

Point ::= SEQUENCE {
    x Int32,
    y Int32
}

List ::= SEQUENCE (SIZE (2)) OF Int32

Nested0 ::= SEQUENCE {
    p Point,
    l List
}

Nested1 ::= SEQUENCE {
    c Nested0
}

Nested2 ::= SEQUENCE {
    b Nested1
}

Nested3 ::= SEQUENCE {
    a Nested2
}

END
